apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-api
  labels:
    app: communication-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-api
  template:
    metadata:
      labels:
        app: communication-api
    spec:
      containers:
      - name: api
        image: communication:v1
        imagePullPolicy: Never # Forces k8s to use your local docker image build
        ports:
        - containerPort: 8090
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8090"
---
apiVersion: v1
kind: Service
metadata:
  name: communication-api-service
spec:
  type: NodePort # This exposes it to your local network/Angular app
  selector:
    app: communication-api
  ports:
    - protocol: TCP
      port: 8090       # Port inside the cluster
      targetPort: 8090 # Port the container listens on
      nodePort: 30090  # Port accessible from your host/Angular (192.168.1.16:30090)