apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:

    # ==========================================================
    # FIXED: Added explicit mapping rules for spanmetrics
    # ==========================================================
    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [100ms, 250ms, 500ms, 1s, 5s]
        dimensions:
          - name: http.request.method
          - name: http.response.status_code
          - name: http.route
          - name: service.name

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "spanmetrics" # Adds a prefix so they are clean to find
      otlp:
        endpoint: "jaeger:4317"
        tls:
          insecure: true
      debug:
        verbosity: detailed
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, debug, spanmetrics]
        metrics:
          receivers: [otlp, spanmetrics]
          processors: [batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, loki]